rm(list = ls())
gc()

## Parallel simulation for RBC-DGM generated data.
##
## This script mirrors run_simulation_parallel.R, but data are generated by
## simulate_rbc_dgm() rather than simulate_gop_dgm_getTwo().
##
## Select a parameter set with GOP_PARAM_SET, e.g. small_1 or normal_3.
##
## Output:
##   measures_results_rbc_dgm_n_<n>_<param_set>.csv
##   cell_probability_results_rbc_dgm_n_<n>_<param_set>.csv
##   cell_probability_true_values_rbc_dgm_n_<n>_<param_set>.csv
##   simulation_results_rbc_dgm_n_<n>_<param_set>.rds

get_script_dir <- function() {
  cmd_args <- commandArgs(trailingOnly = FALSE)
  file_arg <- "--file="
  match <- grep(file_arg, cmd_args, fixed = TRUE)

  if (length(match) > 0) {
    return(dirname(normalizePath(sub(file_arg, "", cmd_args[match[1]]),
                                 winslash = "/", mustWork = TRUE)))
  }

  normalizePath(getwd(), winslash = "/", mustWork = TRUE)
}

get_int_env <- function(name, default) {
  value <- Sys.getenv(name, unset = "")
  if (!nzchar(value)) return(default)

  value <- suppressWarnings(as.integer(value))
  if (is.na(value) || value < 1) default else value
}

get_num_env <- function(name, default) {
  value <- Sys.getenv(name, unset = "")
  if (!nzchar(value)) return(default)

  value <- suppressWarnings(as.numeric(value))
  if (is.na(value)) default else value
}

get_num_vector_env <- function(name, default) {
  value <- Sys.getenv(name, unset = "")
  if (!nzchar(value)) return(default)

  value <- suppressWarnings(as.numeric(strsplit(value, ",", fixed = TRUE)[[1]]))
  if (any(is.na(value))) default else value
}

file_tag_number <- function(x) {
  out <- format(x, scientific = FALSE, trim = TRUE)
  out <- gsub("-", "m", out, fixed = TRUE)
  gsub("\\.", "p", out)
}

detect_default_workers <- function() {
  cores <- parallel::detectCores(logical = FALSE)
  if (is.na(cores)) cores <- parallel::detectCores(logical = TRUE)
  if (is.na(cores)) cores <- 2L
  max(1L, cores - 5L)
}

normalize_param_set_name <- function(x) {
  tolower(gsub("[^A-Za-z0-9]", "", x))
}

resolve_param_set <- function(name, param_sets) {
  keys <- names(param_sets)
  normalized_keys <- normalize_param_set_name(keys)
  normalized_name <- normalize_param_set_name(name)
  match <- which(normalized_keys == normalized_name)

  if (length(match) != 1) {
    stop(
      "Unknown GOP_PARAM_SET: ", name,
      ". Available options are: ", paste(keys, collapse = ", "),
      call. = FALSE
    )
  }

  out <- param_sets[[match]]
  attr(out, "name") <- keys[match]
  out
}

source_project_files <- function(project_dir, files) {
  for (f in files) source(file.path(project_dir, f), local = FALSE)
  invisible(TRUE)
}

bind_rows_base <- function(rows) {
  rows <- Filter(Negate(is.null), rows)
  if (length(rows) == 0) return(data.frame())
  do.call(rbind, rows)
}

ensure_output_dir <- function(path) {
  path <- normalizePath(path, winslash = "/", mustWork = FALSE)

  ok <- dir.exists(path) || suppressWarnings(dir.create(
    path,
    showWarnings = FALSE,
    recursive = TRUE
  ))

  if (ok) {
    test_file <- tempfile("write_test_", tmpdir = path)
    ok <- tryCatch({
      writeLines("ok", test_file)
      unlink(test_file)
      TRUE
    }, error = function(e) FALSE, warning = function(w) FALSE)
  }

  if (isTRUE(ok)) return(path)

  fallback <- file.path(Sys.getenv("TEMP", unset = tempdir()),
                        "gop_two_modules_parallel")
  fallback <- normalizePath(fallback, winslash = "/", mustWork = FALSE)
  ok <- dir.exists(fallback) || dir.create(fallback, recursive = TRUE)
  if (!ok) stop("Cannot create output directory: ", fallback, call. = FALSE)

  warning(
    "Cannot write to requested output directory: ", path,
    ". Using temporary directory instead: ", fallback,
    call. = FALSE
  )
  fallback
}

cell_prob_table <- function(prob, sim_id, seed, method, ids) {
  prob <- as.data.frame(prob)
  names(prob) <- c("p00", "p10", "p01", "p11")
  data.frame(
    sim_id = sim_id,
    seed = seed,
    method = method,
    id = ids,
    p00 = prob$p00,
    p10 = prob$p10,
    p01 = prob$p01,
    p11 = prob$p11,
    row.names = NULL
  )
}

measure_table <- function(result, fit, sim_id, seed, method, measures,
                          true_log_effect) {
  contrast <- c("p10_p00", "p01_p00", "p11_p10")
  log_estimate <- as.numeric(result$measures$mea.point)
  ci_low <- as.numeric(result$measures$mea.CI.low)
  ci_up <- as.numeric(result$measures$mea.CI.up)

  data.frame(
    sim_id = sim_id,
    seed = seed,
    method = method,
    contrast = contrast,
    measure = unname(normalize_measures(measures)),
    log_estimate = log_estimate,
    se = as.numeric(result$measures$mea.se),
    ci_low = ci_low,
    ci_up = ci_up,
    p_value = as.numeric(result$measures$mea.p),
    estimate = exp(log_estimate),
    ci_low_exp = exp(ci_low),
    ci_up_exp = exp(ci_up),
    true_log_effect = true_log_effect,
    true_effect = exp(true_log_effect),
    bias_log = log_estimate - true_log_effect,
    converged = isTRUE(fit$convergence),
    fit_value = fit$value %||% NA_real_,
    row.names = NULL
  )
}

run_one_simulation <- function(sim_id, simulation_args, measures, methods_to_run,
                               base_seed, true_log_effect) {
  seed <- base_seed + sim_id
  set.seed(seed)

  data_rbc <- do.call(simulate_rbc_dgm, simulation_args)
  dat <- standardize_sim_data(data_rbc)

  true_cell_prob <- cell_prob_table(
    prob = cbind(dat$p00, dat$p10, dat$p01, dat$p11),
    sim_id = sim_id,
    seed = seed,
    method = "truth",
    ids = dat$id
  )

  measure_rows <- list()
  cell_prob_rows <- list()
  error_rows <- list()

  if ("RBC" %in% methods_to_run) {
    rbc_out <- tryCatch({
      fit_rbc <- fit_rbc_method(dat)
      pred_rbc <- predict_rbc_method(fit_rbc, dat, measures = measures)
      result_rbc <- evalu_rbc_CM(fit_rbc, pred_rbc)

      list(
        measures = measure_table(result_rbc, fit_rbc, sim_id, seed, "RBC",
                                 measures, true_log_effect),
        cell_prob = cell_prob_table(result_rbc$cellprob, sim_id, seed, "RBC",
                                    dat$id)
      )
    }, error = function(e) {
      list(error = conditionMessage(e))
    })

    if (is.null(rbc_out$error)) {
      measure_rows[["RBC"]] <- rbc_out$measures
      cell_prob_rows[["RBC"]] <- rbc_out$cell_prob
    } else {
      error_rows[["RBC"]] <- data.frame(
        sim_id = sim_id,
        seed = seed,
        method = "RBC",
        error = rbc_out$error,
        row.names = NULL
      )
    }
  }

  if ("gOP" %in% methods_to_run) {
    gop_out <- tryCatch({
      fit_gop <- fit_gop_method(dat, measures = measures)
      result_gop <- evalu_gOP_CM(fit_gop)

      list(
        measures = measure_table(result_gop, fit_gop, sim_id, seed, "gOP",
                                 measures, true_log_effect),
        cell_prob = cell_prob_table(result_gop$cellprob, sim_id, seed, "gOP",
                                    dat$id)
      )
    }, error = function(e) {
      list(error = conditionMessage(e))
    })

    if (is.null(gop_out$error)) {
      measure_rows[["gOP"]] <- gop_out$measures
      cell_prob_rows[["gOP"]] <- gop_out$cell_prob
    } else {
      error_rows[["gOP"]] <- data.frame(
        sim_id = sim_id,
        seed = seed,
        method = "gOP",
        error = gop_out$error,
        row.names = NULL
      )
    }
  }

  list(
    measures = bind_rows_base(measure_rows),
    cell_prob = bind_rows_base(cell_prob_rows),
    true_cell_prob = true_cell_prob,
    errors = bind_rows_base(error_rows)
  )
}

project_dir <- get_script_dir()
setwd(project_dir)

source_files <- c(
  "01_utils.R",
  "02_probabilities.R",
  "03_likelihood.R",
  "04_variance.R",
  "05_estimator.R",
  "simuData.R",
  "simu_evaluation.R"
)
source_project_files(project_dir, source_files)

param_sets <- list(
  small_1 = list(
    target_cellprob = c(p00 = 0.06, p10 = 0.08, p01 = 0.10, p11 = 0.13),
    b0.true = 0.2877,
    b1.true = 0.5543,
    b2.true = 0.5414,
    b3.true = c(-2.7155, 0.12, -0.08, 0.06)
  ),
  small_3 = list(
    target_cellprob = c(p00 = 0.08, p10 = 0.12, p01 = 0.16, p11 = 0.20),
    b0.true = 0.4055,
    b1.true = 0.7841,
    b2.true = 0.6061,
    b3.true = c(-2.4063, 0.12, -0.08, 0.06)
  ),
  normal_1 = list(
    target_cellprob = c(p00 = 0.35, p10 = 0.43, p01 = 0.48, p11 = 0.56),
    b0.true = 0.2059,
    b1.true = 0.5390,
    b2.true = 0.5230,
    b3.true = c(-0.5740, 0.15, -0.10, 0.08)
  ),
  normal_3 = list(
    target_cellprob = c(p00 = 0.40, p10 = 0.50, p01 = 0.60, p11 = 0.70),
    b0.true = 0.2231,
    b1.true = 0.8109,
    b2.true = 0.8473,
    b3.true = c(-0.3605, 0.15, -0.10, 0.08)
  )
)

n_sim <- get_int_env("GOP_N_SIM", 800L)
n <- get_int_env("GOP_N", 200L)
base_seed <- get_int_env("GOP_BASE_SEED", 2026L)
n_workers <- min(n_sim, get_int_env("GOP_N_WORKERS", detect_default_workers()))
param_set_requested <- Sys.getenv("GOP_PARAM_SET", unset = "small_1")
param_set <- resolve_param_set(param_set_requested, param_sets)
param_set_name <- attr(param_set, "name")
param_set_tag <- normalize_param_set_name(param_set_name)
target_cellprob <- param_set$target_cellprob
b0_true <- param_set$b0.true
b1_true <- param_set$b1.true
b2_true <- param_set$b2.true
b3_true <- param_set$b3.true

measures <- c("RR", "OR", "OR")
methods_to_run <- c("RBC", "gOP")

if ("RBC" %in% methods_to_run && !requireNamespace("rbc", quietly = TRUE)) {
  warning("Package 'rbc' is not installed. RBC simulations will be skipped.")
  methods_to_run <- setdiff(methods_to_run, "RBC")
}

if (length(methods_to_run) == 0) {
  stop("No simulation methods are available to run.", call. = FALSE)
}

simulation_args <- list(
  n = n,
  f0 = ~ 1,
  f1 = ~ 1,
  f2 = ~ 1,
  f3 = ~ 1 + z1 + z2 + z3,
  b0.true = c(b0_true),
  b1.true = c(b1_true),
  b2.true = c(b2_true),
  b3.true = b3_true,
  design = c("factorial"),
  pi0 = 0.5,
  pi1 = 0.5,
  randomized = TRUE,
  eps = 1e-8
)

true_log_effect <- c(
  simulation_args$b0.true[1],
  simulation_args$b1.true[1],
  simulation_args$b2.true[1]
)

output_dir <- Sys.getenv(
  "GOP_OUTPUT_DIR",
  unset = file.path(project_dir, "simulation_output_parallel")
)
output_dir <- ensure_output_dir(output_dir)

scenario_tag <- Sys.getenv("GOP_SCENARIO_TAG", unset = "")
if (!nzchar(scenario_tag)) {
  scenario_tag <- paste0("rbc_dgm_n_", n, "_", param_set_tag)
}
scenario_tag <- gsub("[^A-Za-z0-9_.-]", "_", scenario_tag)

add_scenario_columns <- function(df) {
  if (nrow(df) == 0) return(df)
  cbind(
    scenario = scenario_tag,
    dgm = "RBC",
    param_set = param_set_name,
    n = n,
    target_p00 = target_cellprob[["p00"]],
    target_p10 = target_cellprob[["p10"]],
    target_p01 = target_cellprob[["p01"]],
    target_p11 = target_cellprob[["p11"]],
    b0_true = b0_true,
    b1_true = b1_true,
    b2_true = b2_true,
    b3_0_true = b3_true[1],
    b3_1_true = b3_true[2],
    b3_2_true = b3_true[3],
    b3_3_true = b3_true[4],
    df
  )
}

cat("Running RBC-DGM ", n_sim, " simulations with n = ", n,
    " on ", n_workers, " worker(s).\n", sep = "")
cat("Parameter set: ", param_set_name, "\n", sep = "")
cat("Target cell probabilities: ",
    paste(names(target_cellprob), target_cellprob, sep = "=", collapse = ", "),
    "\n", sep = "")
cat("True log effects: b0 = ", b0_true,
    ", b1 = ", b1_true,
    ", b2 = ", b2_true, "\n", sep = "")
cat("b3.true = ", paste(b3_true, collapse = ", "), "\n", sep = "")
cat("Scenario tag: ", scenario_tag, "\n", sep = "")
cat("Methods: ", paste(methods_to_run, collapse = ", "), "\n", sep = "")
cat("Output directory: ", output_dir, "\n", sep = "")

sim_ids <- seq_len(n_sim)

if (n_workers == 1L) {
  sim_results <- lapply(
    sim_ids,
    run_one_simulation,
    simulation_args = simulation_args,
    measures = measures,
    methods_to_run = methods_to_run,
    base_seed = base_seed,
    true_log_effect = true_log_effect
  )
} else {
  cl <- parallel::makeCluster(n_workers)
  on.exit(parallel::stopCluster(cl), add = TRUE)

  parallel::clusterExport(
    cl,
    varlist = c(
      "project_dir", "source_files", "source_project_files",
      "bind_rows_base", "cell_prob_table", "measure_table",
      "run_one_simulation"
    ),
    envir = environment()
  )

  parallel::clusterEvalQ(cl, {
    setwd(project_dir)
    source_project_files(project_dir, source_files)
    NULL
  })

  sim_results <- parallel::parLapplyLB(
    cl,
    sim_ids,
    run_one_simulation,
    simulation_args = simulation_args,
    measures = measures,
    methods_to_run = methods_to_run,
    base_seed = base_seed,
    true_log_effect = true_log_effect
  )
}

measures_results <- bind_rows_base(lapply(sim_results, `[[`, "measures"))
cell_probability_results <- bind_rows_base(lapply(sim_results, `[[`, "cell_prob"))
cell_probability_true_values <- bind_rows_base(lapply(sim_results, `[[`, "true_cell_prob"))
simulation_errors <- bind_rows_base(lapply(sim_results, `[[`, "errors"))

measures_results <- add_scenario_columns(measures_results)
cell_probability_results <- add_scenario_columns(cell_probability_results)
cell_probability_true_values <- add_scenario_columns(cell_probability_true_values)
simulation_errors <- add_scenario_columns(simulation_errors)

measures_file <- file.path(output_dir, paste0("measures_results_", scenario_tag, ".csv"))
cell_probability_file <- file.path(
  output_dir,
  paste0("cell_probability_results_", scenario_tag, ".csv")
)
cell_probability_true_file <- file.path(
  output_dir,
  paste0("cell_probability_true_values_", scenario_tag, ".csv")
)
simulation_errors_file <- file.path(
  output_dir,
  paste0("simulation_errors_", scenario_tag, ".csv")
)
simulation_results_file <- file.path(
  output_dir,
  paste0("simulation_results_", scenario_tag, ".rds")
)

write.csv(measures_results, file = measures_file, row.names = FALSE)
write.csv(cell_probability_results, file = cell_probability_file, row.names = FALSE)
write.csv(cell_probability_true_values, file = cell_probability_true_file,
          row.names = FALSE)

if (nrow(simulation_errors) > 0) {
  write.csv(simulation_errors, file = simulation_errors_file, row.names = FALSE)
  warning("Some simulations failed. See ", simulation_errors_file, ".")
}

# saveRDS(
#   list(
#     measures_results = measures_results,
#     cell_probability_results = cell_probability_results,
#     cell_probability_true_values = cell_probability_true_values,
#     simulation_errors = simulation_errors,
#     config = list(
#       dgm = "RBC",
#       n_sim = n_sim,
#       n = n,
#       param_set = param_set_name,
#       target_cellprob = target_cellprob,
#       b0_true = b0_true,
#       b1_true = b1_true,
#       b2_true = b2_true,
#       b3_true = b3_true,
#       scenario_tag = scenario_tag,
#       base_seed = base_seed,
#       n_workers = n_workers,
#       measures = measures,
#       methods_to_run = methods_to_run,
#       simulation_args = simulation_args
#     )
#   ),
#   file = simulation_results_file
# )

cat("Finished.\n")
cat("Wrote: ", measures_file, "\n", sep = "")
cat("Wrote: ", cell_probability_file, "\n", sep = "")
cat("Wrote: ", cell_probability_true_file, "\n", sep = "")
